#!/bin/bash

yarn ts-node healthpointLocationsOpenNow.ts > /home/ec2-user/vaxxnzlocationshealthpoint.log 2>&1
git add .
git commit -m "updated healthpoint from $(TZ='Pacific/Auckland' date)"
git pull --rebase
git push
