#!/bin/bash

cd "$(dirname "$0")"
echo "started availability.js"
NODE_ENV=production node ./lib/availability.js > /home/ubuntu/vaxxnzlocations.log 2>&1
if [ $? -eq 0 ]; then
    echo "index.js (locations job) completed successfully"
    git add .
    git commit -m "updated from $(TZ='Pacific/Auckland' date)"
    git pull --rebase
    git push
else
    echo "index.js (locations job) failed. skipping."
    git fetch
    git reset --hard origin/main
    exit 1
fi