#!/bin/bash

cd "$(dirname "$0")"
echo "started healthpointLocationsOpenNow.ts"
NODE_ENV=production yarn ts-node ./lib/healthpointLocationsOpenNow.ts > /home/ubuntu/vaxxnzlocationshealthpoint.log 2>&1
if [ $? -eq 0 ]; then
    echo "healthpointLocationsOpenNow.ts completed successfully"
    git add .
    git commit -m "updated healthpoint from $(TZ='Pacific/Auckland' date)"
    git pull --rebase
    git push
else
    echo "healthpointLocationsOpenNow.ts failed. skipping."
    git fetch
    git reset --hard origin/main
    exit 1
fi
